
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2.7
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : jesd204b_rx4_exdes.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## USER CONSTRAINTS FILE FOR MGT WRAPPER EXAMPLE DESIGN
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## Device:  xc7a200t
## Package: fbg676
##
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

 

################################## Clock Constraints ##########################


####################### GT reference clock constraints #######################
# create_clock -name q0_clk0_refclk_i -period 8.138 q0_clk0_refclk_i

    
# DRP Clock Constraint
create_clock -name drpclk_in_i -period 10.0 [get_ports DRP_CLK_IN]
create_clock -name SYSCLK_IN -period 10.0 [get_ports SYSCLK_IN]

# User Clock Constraints
create_clock -name gt0_txusrclk_i -period 6.51 [get_pins -hier -filter {name=~*gt0_jesd204b_rx4_i*gtpe2_i*TXOUTCLK}]
create_clock -name gt0_rxusrclk_i -period 8.138 [get_pins -hier -filter {name=~*gt0_jesd204b_rx4_i*gtpe2_i*RXOUTCLK}]

create_clock -name gt1_txusrclk_i -period 6.51 [get_pins -hier -filter {name=~*gt1_jesd204b_rx4_i*gtpe2_i*TXOUTCLK}]
create_clock -name gt1_rxusrclk_i -period 8.138 [get_pins -hier -filter {name=~*gt1_jesd204b_rx4_i*gtpe2_i*RXOUTCLK}]

create_clock -name gt2_txusrclk_i -period 6.51 [get_pins -hier -filter {name=~*gt2_jesd204b_rx4_i*gtpe2_i*TXOUTCLK}]
create_clock -name gt2_rxusrclk_i -period 8.138 [get_pins -hier -filter {name=~*gt2_jesd204b_rx4_i*gtpe2_i*RXOUTCLK}]

create_clock -name gt3_txusrclk_i -period 6.51 [get_pins -hier -filter {name=~*gt3_jesd204b_rx4_i*gtpe2_i*TXOUTCLK}]
create_clock -name gt3_rxusrclk_i -period 8.138 [get_pins -hier -filter {name=~*gt3_jesd204b_rx4_i*gtpe2_i*RXOUTCLK}]


################################# RefClk Location constraints #####################
set_property LOC AB13 [get_ports Q0_CLK0_GTREFCLK_PAD_N_IN ]
set_property LOC AA13 [get_ports Q0_CLK0_GTREFCLK_PAD_P_IN ]

################################# mgt wrapper constraints #####################

##---------- Set placement for gt0_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y0 [get_cells jesd204b_rx4_init_i/jesd204b_rx4_i/gt0_jesd204b_rx4_i/gtpe2_i]
##---------- Set placement for gt1_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y1 [get_cells jesd204b_rx4_init_i/jesd204b_rx4_i/gt1_jesd204b_rx4_i/gtpe2_i]
##---------- Set placement for gt2_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y2 [get_cells jesd204b_rx4_init_i/jesd204b_rx4_i/gt2_jesd204b_rx4_i/gtpe2_i]
##---------- Set placement for gt3_gtp_wrapper_i/GTPE2_CHANNEL ------
set_property LOC GTPE2_CHANNEL_X0Y3 [get_cells jesd204b_rx4_init_i/jesd204b_rx4_i/gt3_jesd204b_rx4_i/gtpe2_i]

##---------- Set ASYNC_REG for flop which have async input ----------
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_gen*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt0_frame_check*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_gen*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt1_frame_check*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_gen*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt2_frame_check*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_gen*system_reset_r_reg}]
set_property ASYNC_REG TRUE [get_cells -hier -filter {name=~*gt3_frame_check*system_reset_r_reg}]

##---------- Set False Path from one clock to other ----------
set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt0_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt0_txusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt0_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt0_rxusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt0_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt0_txusrclk_i"] -to [get_clocks "drpclk_in_i"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt0_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt0_rxusrclk_i"] -to [get_clocks "drpclk_in_i"]

##set_false_path -from [get_clocks "gt0_rxusrclk_i"] -to [get_clocks "gt0_rxusrclk2_i"]
##set_false_path -from [get_clocks "gt0_rxusrclk2_i"] -to [get_clocks "gt0_rxusrclk_i"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt1_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt1_txusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt1_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt1_rxusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt1_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt1_txusrclk_i"] -to [get_clocks "drpclk_in_i"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt1_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt1_rxusrclk_i"] -to [get_clocks "drpclk_in_i"]

##set_false_path -from [get_clocks "gt1_rxusrclk_i"] -to [get_clocks "gt1_rxusrclk2_i"]
##set_false_path -from [get_clocks "gt1_rxusrclk2_i"] -to [get_clocks "gt1_rxusrclk_i"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt2_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt2_txusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt2_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt2_rxusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt2_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt2_txusrclk_i"] -to [get_clocks "drpclk_in_i"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt2_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt2_rxusrclk_i"] -to [get_clocks "drpclk_in_i"]

##set_false_path -from [get_clocks "gt2_rxusrclk_i"] -to [get_clocks "gt2_rxusrclk2_i"]
##set_false_path -from [get_clocks "gt2_rxusrclk2_i"] -to [get_clocks "gt2_rxusrclk_i"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt3_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt3_txusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "SYSCLK_IN"] -to [get_clocks -include_generated_clocks "gt3_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt3_rxusrclk_i"] -to [get_clocks "SYSCLK_IN"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt3_txusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt3_txusrclk_i"] -to [get_clocks "drpclk_in_i"]

set_false_path -from [get_clocks "drpclk_in_i"] -to [get_clocks -include_generated_clocks "gt3_rxusrclk_i"]
set_false_path -from [get_clocks -include_generated_clocks "gt3_rxusrclk_i"] -to [get_clocks "drpclk_in_i"]

##set_false_path -from [get_clocks "gt3_rxusrclk_i"] -to [get_clocks "gt3_rxusrclk2_i"]
##set_false_path -from [get_clocks "gt3_rxusrclk2_i"] -to [get_clocks "gt3_rxusrclk_i"]



